# Generated by Django 5.2.1 on 2025-05-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingan',
            name='total_comment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postingan',
            name='total_like',
            field=models.IntegerField(default=0),
        ),
    ]
