# Generated by Django 5.2.1 on 2025-05-27 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_postingan_total_comment_postingan_total_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='komentar',
            old_name='question',
            new_name='post_id',
        ),
        migrations.RemoveField(
            model_name='postingan',
            name='total_like',
        ),
        migrations.CreateModel(
            name='Suka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='home.postingan')),
            ],
            options={
                'unique_together': {('user_id', 'post_id')},
            },
        ),
    ]
