# Generated by Django 5.2.1 on 2025-05-27 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_question_komentar_post_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postingan',
            old_name='total_comment',
            new_name='total_share',
        ),
        migrations.AlterField(
            model_name='komentar',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.postingan'),
        ),
    ]
