# Generated by Django 5.2.1 on 2025-05-29 05:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_total_comment_postingan_total_share_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentar',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
