# Generated by Django 5.2.1 on 2025-05-31 22:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_komentar_pub_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postingan',
            name='user_id',
        ),
        migrations.AddField(
            model_name='postingan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postingan',
            name='uploader_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_uploader_images'),
        ),
        migrations.AddField(
            model_name='postingan',
            name='uploader_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='postingan',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
